trigger:
- main

# jobs:
# - job: myJob
#   timeoutInMinutes: 10
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - bash: echo "Hello world"

jobs:
- job: test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
    condition: 
# - task: CmdLine@2
#   inputs:
#     script: 'cd ./api'

  - script: |
      yarn
    displayName: 'yarn install'

  - script: |
      yarn test
    displayName: 'yarn test'

#   - script: |
#       npm uninstall *
#     displayName: 'Clean packages'
#   -job: Deploy
- job: deploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'EP-Server'
      contents: '**'
      targetFolder: '/api'
      readyTimeout: '20000'

