trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
  condition: 
# - task: CmdLine@2
#   inputs:
#     script: 'cd ./api'

- script: |
    yarn install
  displayName: 'npm ci'

- script: |
    yarn test
  displayName: 'yarn test'

