version: '3.8'

# networks: 
#   ep-mern: 
#     external: true

services:

  api:
    image: ep-mern-api
    container_name: ep-mern-api
    # stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /api/node_modules
      - ./api:/app
    ports:
      - "3000:3000"
    # networks: 
    #   - ep-mern