apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep-mern-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep-mern-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ep-mern-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ep-mern-api
        image: azurecontainerlorde.azurecr.io/ep-mern-api:${BUILD_TAG}
        envFrom: 
        - configMapRef:
            name: ep-config-map
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: ep-mern-api 
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: ep-mern-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  ep-mern-api
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host:  ep-mern-api.k8s-test-2-dns-czux3v9j.hcp.swedencentral.azmk8s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: ep-mern-api
            port: 
              number: 3000